CREATE SCHEMA MUDB;

USE MUDB;

CREATE TABLE MUDB_USER (
  Username VARCHAR(50) PRIMARY KEY,
  Password VARCHAR(255) NOT NULL,
  Role VARCHAR(50) NOT NULL,
  Email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE ARTIST (
  ArtistID INT AUTO_INCREMENT PRIMARY KEY,
  DateOfBirth DATE,
  Name VARCHAR(255) NOT NULL
);

CREATE TABLE SONG (
  SongID INT AUTO_INCREMENT PRIMARY KEY,
  Duration INT,
  Title VARCHAR(255) NOT NULL,
  Username VARCHAR(50) NOT NULL,
  FOREIGN KEY (Username) REFERENCES MUDB_USER(Username)
);

CREATE TABLE ALBUM (
  AlbumID INT AUTO_INCREMENT PRIMARY KEY,
  ReleaseDate DATE,
  Title VARCHAR(255) NOT NULL,
  ArtistID INT NOT NULL,
  FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID)
);

CREATE TABLE RATING (
  RatingID INT AUTO_INCREMENT PRIMARY KEY,
  Score INT NOT NULL,
  Username VARCHAR(50) NOT NULL,
  SongID INT NOT NULL,
  UNIQUE (Username, SongID),
  FOREIGN KEY (Username) REFERENCES MUDB_USER(Username),
  FOREIGN KEY (SongID) REFERENCES SONG(SongID)
);

CREATE TABLE CONTAINS (
  SongID INT NOT NULL,
  AlbumID INT NOT NULL,
  TrackNumber INT NOT NULL,
  PRIMARY KEY (SongID, AlbumID),
  UNIQUE (AlbumID, TrackNumber),
  FOREIGN KEY (SongID) REFERENCES SONG(SongID),
  FOREIGN KEY (AlbumID) REFERENCES ALBUM(AlbumID)
);

CREATE TABLE SONG_GENERE (
  SongID INT NOT NULL,
  Genre VARCHAR(50) NOT NULL,
  PRIMARY KEY (SongID, Genre),
  FOREIGN KEY (SongID) REFERENCES SONG(SongID)
);

CREATE TABLE SONG_LANGUAGE (
  SongID INT NOT NULL,
  Language VARCHAR(50) NOT NULL,
  PRIMARY KEY (SongID, Language),
  FOREIGN KEY (SongID) REFERENCES SONG(SongID)
);

CREATE TABLE FEATURES (
  ArtistID INT NOT NULL,
  SongID INT NOT NULL,
  PRIMARY KEY (ArtistID, SongID),
  FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID),
  FOREIGN KEY (SongID) REFERENCES SONG(SongID)
);
